<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <Copyright>© Jerem'Tech</Copyright>
    <UseWindowsForms>True</UseWindowsForms>
    <StartupObject>FMH.Core.App</StartupObject>
    <Authors>Jerem'Tech</Authors>
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FMH.Resources\FMH.Resources.csproj" />
    <ProjectReference Include="..\FMH.Workspace\FMH.Workspace.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="$(CommunityToolkitMvvmVersion)" />
    <PackageReference Include="ConsoleControl.WPF" Version="$(ConsoleControlVersion)" />
    <PackageReference Include="FontAwesome.WPF" Version="$(FontAwesomeVersion)" />
    <PackageReference Include="McVersionsLib" Version="$(McVersionLibVersion)" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Leow.TextEditor">
      <HintPath>..\Leow.TextEditor.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
